version: '3'

services:
  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_database_user
      POSTGRES_PASSWORD: my_database_password
    ports:
      - "5432:5432"
  
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "1111:1111"
    depends_on:
      - db
