version: '3'

services:
  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: geo_db
      POSTGRES_USER: geo_user
      POSTGRES_PASSWORD: geo_password
    ports:
      - "5432:5432"
  
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "1111:1111"
    depends_on:
      - db
