# Generated by Django 4.2.3 on 2023-07-28 10:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geometry_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Координаты')),
            ],
            options={
                'verbose_name': 'Округ',
                'verbose_name_plural': 'Округи',
            },
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Координаты')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_region', to='geometry_app.region')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Contour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Координаты')),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contour_canton', to='geometry_app.canton')),
            ],
            options={
                'verbose_name': 'Контур',
                'verbose_name_plural': 'Контуры',
            },
        ),
        migrations.AddField(
            model_name='canton',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canton_district', to='geometry_app.district'),
        ),
    ]
